config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?
  post '/graphql', to: 'graphql#execute'
  devise_for :users,
             path: 'users',
             path_names: {
               sign_in: 'signin',
               sign_out: 'signout',
               sign_up: 'signup'
             },
             sign_out_via: 'get'
  mount Sidekiq::Web => '/sidekiq'
  get 'users/snippets', to: 'snippets#user_list', as: :list_user_snippets
  resources :snippets, only: %i[show create], path: ''
  root 'snippets#new'
end

app/views/layouts/_messages.html.erb
<% if flash.keys.length > 0 %>
<div id="flash_messages">
  <% flash.each do |name, msg| %>
  <div class="message" data-name="<%= name %>" data-msg="<%= msg %>"></div>
  <% end %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, maximum-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) + " - Pasty" : "Pasty - " + _("The paste tool you'll love") %></title>
    <meta name="description" content="<%= content_for?(:meta_description) ? yield(:meta_description) : '' %>" />
    <meta name="keywords" content="<%= content_for?(:meta_keywords) ? yield(:meta_keywords) : '' %>" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'App' %>
    <%= stylesheet_pack_tag 'App', media: 'all' %>
    <%= yield(:head) %>
  </head>

  <body
    id="<%= content_for?(:body_id) ? yield(:body_id) : '' %>"
    class="<%= content_for?(:body_class) ? yield(:body_class) : '' %>"
    data-controller="<%= content_for?(:data_controller) ? yield(:data_controller) : '' %>"
    data-action="<%= content_for?(:data_action) ? yield(:data_action) : '' %>"
  >
    <div id="wrap">
      <% if content_for?(:navbar) %>
        <%= yield(:navbar) %>
      <% else %>
      <div id="navbar_wrapper" class="has-background-primary">
        <div class="container is-fluid">
          <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
              <a class="navbar-item" href="<%= root_path %>">
                <img src="<%= asset_pack_path 'images/pasty_logo.svg' %>" alt="Pasty logo" />
              </a>
              <div class="navbar-burger">
                <span></span>
                <span></span>
                <span></span>
              </div>
            </div>
            <div id="pasty_navbar" class="navbar-menu">
              <div class="navbar-start">
                <a class="navbar-item"><%= _('About') %></a>
              </div>
              <div class="navbar-end">
              </div>
            </div>
            <div class="navbar-end">
              <% if user_signed_in? %>
              <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link"><i data-feather="user"></i></a>
                <div class="navbar-dropdown is-right">
                  <a href="<%= edit_user_registration_path %>" class="navbar-item">
                    <i data-feather="settings" width="20px" class="is-mr-2"></i><%= _('Settings') %>
                  </a>
                  <a href="<%= list_user_snippets_path %>" class="navbar-item">
                    <i data-feather="code" width="20px" class="is-mr-2"></i><%= _('My snippets') %>
                  </a>
                  <hr class="navbar-divider">
                  <a href="<%= destroy_user_session_path %>" class="navbar-item">
                    <i data-feather="log-out" width="20px" class="is-mr-2"></i><%= _('Log out') %>
                  </a>
                </div>
              </div>
              <% else %>
              <div class="navbar-item">
                <div class="buttons">
                  <a href="<%= new_user_registration_path %>" class="button is-primary"><strong><%= _('Sign up') %></strong></a>
                  <a href="<%= new_user_session_path %>" class="button is-light"><%= _('Log in') %></a>
                </div>
              </div>
              <% end %>
            </div>
          </nav>
        </div>
      </div>
      <% end %>
      <%= render 'layouts/messages' %>
      <%= yield %>
      <footer id="footer" class="footer">
        <div class="container">
          <div class="content has-text-centered">
            <p class="copyright">&copy; Pasty <%= Date.today.year %></p>
          </div>
        </div>
      </footer>
    </div>
    <%= javascript_pack_tag 'App' %>
  </body>
</html>